### ISSUE TITLE
can i update the kernel version ?

### ISSUE THREAD

**Issue by cailiangliang765** [WhitewaterFoundry/Pengwin-Enterprise#52]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by crramirez** [comment]
Hello,

No, you can't. With WSL 1 is the Microsoft kernel for Linux compatibility, it only changes with a Windows upgrade. And with WSL 2 the Linux kernel is provided by Microsoft as well.

And to try to help you. Why do you would need to upgrade the WSL's kernel?

Regards

**Comment by cailiangliang765** [comment]
> Hello,
> 
> No, you can't. With WSL 1 is the Microsoft kernel for Linux compatibility, it only changes with a Windows upgrade. And with WSL 2 the Linux kernel is provided by Microsoft as well.
> 
> And to try to help you. Why do you would need to upgrade the WSL's kernel?
> 
> Regards

I use kernel 5.1.0 on other centos Linux versions.I want to keep the dev environment consistent so I want to upgrade the WSL kernel. 
Another question, I now purchase and use pengwin enterprise version, what is the difference between it and pengwin? Are there any new features added to pengwin?

**Comment by sirredbeard** [comment]
You cannot upgrade the kernel because there is no kernel in WSL1, it is a Linux to NT syscall translation layer. You will have to elaborate on why a specific kernel version matters to your development environment. I can see why specific versions of glibc, gcc, clang, etc. would, but most recent kernels should be fine. If your development relies on specific kernel headers or you want to work on the kernel source then you would install them just like you would normally. But there's no kernel running in WSL1 to replace, please see https://www.pengwin.dev/what-is-wsl and https://github.com/sirredbeard/Awesome-WSL.

Pengwin is our main distribution, it has many new features and tools added, including pengwin-setup, please see https://github.com/WhitewaterFoundry/Pengwin-Enterprise#microsoft-store-build.

**Comment by crramirez** [comment]
Also an important difference is that pengwin enterprise is scientific Linux based compatible with (CentOS, RHEL, Fedora, etc).

Pengwin is Debian based compatible with Ubuntu, Kalo, etc)

**Comment by cailiangliang765** [comment]
> You cannot upgrade the kernel because there is no kernel in WSL1, it is a Linux to NT syscall translation layer. You will have to elaborate on why a specific kernel version matters to your development environment. I can see why specific versions of glibc, gcc, clang, etc. would, but most recent kernels should be fine. If your development relies on specific kernel headers or you want to work on the kernel source then you would install them just like you would normally. But there's no kernel running in WSL1 to replace, please see https://www.pengwin.dev/what-is-wsl and https://github.com/sirredbeard/Awesome-WSL.
> 
> Pengwin is our main distribution, it has many new features and tools added, including pengwin-setup, please see https://github.com/WhitewaterFoundry/Pengwin-Enterprise#microsoft-store-build.

Many thanks for your reply and hoping for wsl2's coming soon !

**Comment by cailiangliang765** [comment]
> Also an important difference is that pengwin enterprise is scientific Linux based compatible with (CentOS, RHEL, Fedora, etc).
> 
> Pengwin is Debian based compatible with Ubuntu, Kalo, etc)
Thanks for your information !

**Comment by sirredbeard** [comment]
WSL2 will be available in the Insiders Fast Ring build in June.
